package bytehala.kata;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lem' at '12/25/16 5:59 PM' with Gradle 3.2.1
 *
 * @author lem, @date 12/25/16 5:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String args[]) {
        System.out.println("Hello world");
    }
}
