package bytehala.kata;

import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'lem' at '12/25/16 5:59 PM' with Gradle 3.2.1
 *
 * @author lem, @date 12/25/16 5:59 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void failingTest() {
        //fail("This test will fail.");
    }
}
